### ISSUE TITLE
カート機能

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-apricot#38]
カートページ
path: POST carts/add_cart
controller#action: carts#show,
参考モックアップ: carts_show.html

削除処理
path: DELETE carts/destroy
controller#action: Users#create

カートへ商品を追加、削除する機能を実装。

注文確定のボタン押下後、注文情報をDBへ格納し、購入画面へ遷移

Cart, CartItemの2テーブルを作成し、カート情報はそこに格納すること。

**Comment by yuki-tachi0219** [comment]
localhost:3000/carts/add_cartとlocalhost:3000/carts/destroyを実行するボタンがあるはずで、それをどの画面に実装するかも定義しましょう！

**Comment by yuki-tachi0219** [comment]
cart, cart_itemテーブルが他のテーブルとどのように関連付けられているかも今のうちに決めたいです。

**Comment by tatata05** [comment]
[cart] 関係:userと1対1、カラム:user_id
[cart_item] 関係:cartと1対多、productと1対多、カラム: cart_id,product_id,quantity

こんなイメージかなと思っています。
